name: onnxruntime_v2
description: Flutter plugin for OnnxRuntime provides an easy, flexible, and fast Dart API to integrate Onnx models in flutter apps across mobile and desktop platforms.
version: 1.23.2
homepage: https://github.com/Persie0/onnxruntime_flutter_1_22_0

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.4

dev_dependencies:
  ffigen: ^20.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # pana: ^0.21.36

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      linux:
        ffiPlugin: true

topics:
  - onnx
  - tflite
  - pytorch
  - ai
